### ISSUE TITLE
unable to run test

### ISSUE THREAD

**Issue by asaki1986** [crp-mol/super-HTS#2]
Hi,

Thanks for providing great tool to predict the binding energy.

I install the tool on mac, following the step provided.

Error was found when I ran the command

`python GCN.py -f datasets/D1.dat -r dock/4e3q.pdb --aa_index AAIndex.csv --train_model`

`Traceback (most recent call last):
  File "/Users/Jiang/work/super-HTS/GCN.py", line 692, in <module>
    main()
  File "/Users/Jiang/work/super-HTS/GCN.py", line 605, in main
    tf.config.experimental.set_virtual_device_configuration(gpus[0], [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=2046)])
IndexError: list index out of range`

Which parameter should I changed to fix this?

Best

**Comment by easyprogramm4ever** [comment]
Hi, I met same problem. If you find the solution, it would be so kind of you to give me some advices!
bests,
